
[lithium]
	register = false
	dimensions = [0, -4848]
	vein_size = 7
	min_height = -60
	max_height = 60

[platinum]
	register = false
	dimensions = [0, -4848]
	vein_size = 7
	min_height = -60
	max_height = 0

[thorium]
	register = false
	dimensions = [0, -4848]
	vein_size = 7
	min_height = -60
	max_height = 60

[tin]
	register = false
	dimensions = [0, -4848]
	vein_size = 7
	min_height = 4
	max_height = 60

[magnesium]
	register = false
	dimensions = [0, -4848]
	vein_size = 7
	min_height = -60
	max_height = 60

[silver]
	register = false
	dimensions = [0, -4848]
	vein_size = 7
	min_height = -60
	max_height = 60

[cobalt]
	register = false
	dimensions = [0, -4848]
	vein_size = 7
	min_height = -60
	max_height = 60

[uranium]
	register = false
	dimensions = [0, -4848]
	vein_size = 7
	min_height = -60
	max_height = 60

[zinc]
	register = false
	dimensions = [0, -4848]
	vein_size = 7
	min_height = 4
	max_height = 60

[boron]
	register = false
	dimensions = [0, -4848]
	vein_size = 7
	min_height = -60
	max_height = 60

[lead]
	register = false
	dimensions = [0, -4848]
	vein_size = 7
	min_height = 4
	max_height = 60

[slurries]
	#List of available slurries (dissolved ores in acid)
	#Color for slurry will be calculate from average texture color
	#Texture location has to be: nuclearcraft:textures/block/ore/(slurry_name)_ore.png
	#If no texture found it will generate random color
	register_slurries = []

[raw_chunks]
	lithium = false
	platinum = false
	thorium = false
	tin = false
	magnesium = false
	silver = false
	cobalt = false
	uranium = false
	zinc = false
	boron = false
	lead = false

[ingots]
	manganese_oxide = false
	niobium_tin = false
	graphite = false
	lithium = false
	platinum = false
	tungsten = false
	zircaloy = false
	yttrium = false
	thermoconducting = true
	thorium = false
	zirconium_molybdenum = false
	tin = false
	palladium = false
	beryllium = false
	silicon_carbide = false
	zinc = false
	carbon_manganese = false
	extreme = true
	shibuichi = false
	tungsten_carbide = false
	stainless_steel = false
	magnesium = false
	bronze = false
	sodium = false
	tin_silver = false
	pyrolitic_carbon = false
	manganese_dioxide = false
	silver = false
	uranium = false
	niobium_titanium = false
	tough_alloy = true
	steel = false
	potassium = false
	ferroboron = true
	titanium = false
	super_alloy = true
	cobalt = false
	aluminum = false
	manganese = false
	sic_sic_cmc = false
	hard_carbon = true
	niobium = false
	zirconium = false
	electrum = false
	chromium = false
	calcium = false
	strontium = false
	osmium = false
	lithium_manganese_dioxide = false
	lead = false
	osmiridium = false
	lead_platinum = false
	hsla_steel = false
	nichrome = false
	boron = false
	magnesium_diboride = false
	hafnium = false

[nuggets]
	steel = false
	electrum = false
	magnesium = false
	cobalt = false
	aluminum = false
	lead = false
	bronze = false
	lithium = false
	platinum = false
	thorium = false
	tin = false
	beryllium = false
	silver = false
	uranium = false
	zirconium = false
	zinc = false
	boron = false

[plates]
	tough_alloy = true
	steel = false
	ferroboron = true
	cobalt = false
	aluminum = false
	graphite = false
	manganese = false
	sic_sic_cmc = false
	netherite = false
	lithium = false
	platinum = false
	thermoconducting = true
	thorium = false
	hard_carbon = true
	tin = false
	palladium = false
	copper = false
	beryllium = false
	zirconium = false
	zinc = false
	extreme = true
	electrum = false
	magnesium = false
	lithium_manganese_dioxide = false
	lead = false
	bronze = false
	iron = false
	silver = false
	hsla_steel = false
	uranium = false
	boron = false

[dusts]
	barium = false
	germanium = false
	tungsten = false
	zircaloy = false
	yttrium = false
	thermoconducting = true
	thorium = false
	zirconium_molybdenum = false
	palladium = false
	sulfur = false
	fluorite = false
	lapis = false
	silicon_carbide = false
	zinc = false
	carbon_manganese = false
	molybdenum = false
	purpur = false
	borax = false
	magnesium = false
	bronze = false
	manganese_dioxide = false
	silver = false
	boron_nitride = false
	gadolinium = false
	tough_alloy = true
	steel = false
	ferroboron = true
	cobalt = false
	strontium_90 = true
	potassium_hydroxide = false
	alugentum = false
	aluminum = false
	manganese = false
	sic_sic_cmc = false
	protactinium_233 = true
	gold = false
	europium_155 = true
	hard_carbon = true
	end_stone = false
	niobium = false
	yellowcake = false
	copper = false
	iodine = false
	zirconium = false
	electrum = false
	caesium_137 = true
	strontium = false
	rhodochrosite = false
	lead = false
	boron_arsenide = true
	neodymium = false
	lead_platinum = false
	crystal_binder = false
	charcoal = false
	hafnium = false
	sodium_hydroxide = false
	manganese_oxide = false
	samarium = false
	erbium = false
	radium = false
	bscco = false
	graphite = false
	netherite = false
	lithium = false
	platinum = false
	carobbiite = false
	tin = false
	beryllium = false
	ruthenium_106 = true
	extreme = true
	shibuichi = false
	obsidian = false
	polonium = false
	arsenic = false
	energetic_blend = false
	sodium = false
	tin_silver = false
	pyrolitic_carbon = false
	potassium_fluoride = false
	coal = false
	uranium = false
	emerald = false
	c_mn_blend = false
	potassium = false
	tbp = false
	ytterbium = false
	titanium = false
	dimensional_blend = false
	thallium = false
	enderium = false
	sodium_fluoride = false
	irradiated_borax = false
	terbium = false
	calcium_sulfate = false
	chromium = false
	promethium_147 = true
	calcium = false
	potassium_iodide = false
	villiaumite = false
	osmium = false
	lithium_manganese_dioxide = false
	quartz = false
	diamond = false
	iron = false
	hsla_steel = false
	boron = false
	bismuth = false

[blocks]
	steel = false
	electrum = false
	supercold_ice = false
	magnesium = false
	cobalt = false
	aluminum = false
	graphite = false
	lead = false
	bronze = false
	californium250 = false
	lithium = false
	platinum = false
	thorium = false
	americium241 = false
	plutonium238 = false
	tin = false
	beryllium = false
	uranium238 = false
	silver = false
	uranium = false
	zirconium = false
	zinc = false
	boron = false

[gems]
	boron_arsenide = false
	carobbiite = false
	silicon = false
	villiaumite = false
	fluorite = false
	rhodochrosite = false
	boron_nitride = false

#Forge Tag priority
[forge_tag_priority]
	#Priority of mods to resolve forge tags to itemstack and fluidstack.
	mods_priority = ["minecraft", "gregtech", "nuclearcraft", "mekanism", "immersiveengineering", "tconstruct"]

